version: '3'
services:
  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_PASSWORD=asdf123
  redis:
    image: 'redis:latest'
  nginx:
    restart: always # Always make sure nginx running
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '3050:80' # Porting from 3050 to 80
    depends_on:
      - api
      - client
  api:
    build:
      dockerfile: Dockerfile.dev # Using dev file
      context: ./server # The location of server's docker file
    volumes:
      - /app/node_modules # Don't overwrite this folder
      - ./server:/app # Copy from server to /app
    environment:
      - REDIS_HOST=redis # Specify the name of service
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=asdf123
      - PGPORT=5432
  worker:
    build:
      dockerfile: Dockerfile.dev
      context: ./worker
    volumes:
      - /app/node_modules
      - ./worker:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WDS_SOCKET_PORT=0
