name: Docker multi-client CI/CD
on: [push]
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - run: docker build -t vinaldorichard/react-test -f ./client/Dockerfile.dev ./client
  test:
    needs: setup # Depends on setup steps
    runs-on: ubuntu-latest
    steps :
      - run: docker run -e CI=true vinaldorichard/react-test npm test
  build:
    needs: test
    runs-on: ubuntu-latest
    env:
      DOCKER_ID: ${{secrets.DOCKER_ID}}
      DOCKER_PASSWORD : ${{secrets.DOCKER_PASSWORD}}
    steps:
      - run: docker build -t vinaldorichard/multi-client ./client
      - run: docker build -t vinaldorichard/multi-nginx ./nginx
      - run: docker build -t vinaldorichard/multi-server ./server
      - run: docker build -t vinaldorichard/multi-worker ./worker
      - run: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
      - run: docker push vinaldorichard/multi-client
      - run: docker push vinaldorichard/multi-nginx
      - run: docker push vinaldorichard/multi-server
      - run: docker push vinaldorichard/multi-worker